JH-81 -- late merge of support/connector/1.2.0 back into release/connector/1.2.4
rticommunity/rticonnextdds-connector-py pull request #185
Opened 2024-10-08 22:20 UTC by alvinkrebs

I've created this PR to expose the possible missing progression of release/connector/1.2.4. Could you guys have a look at the diffs and see if they make sense?

Here's what I did ...

```
# rticonnextdds-connector-py support/1.2.0 -> release/connector/1.2.4
#
git checkout support/connector/1.2.0 && git pull
git checkout release/connector/1.2.4 && git pull
git checkout -b feature/JH-81-gen-1.2.4-sup-1.2.0
git merge support/connector/1.2.0
git push origin feature/JH-81-gen-1.2.4-sup-1.2.0
```

2024-10-08 23:07 UTC, elainerti reviewed
@Alxe or @ManuelJNunez  validation test is failing. Is this normal?

2024-10-09 05:58 UTC, ManuelJNunez commented on resources/jenkins/build_and_test.groovy
> +                    installDirectory: '.',
That change should be there, the validation passed for my PR: https://github.com/rticommunity/rticonnextdds-connector-py/pull/182

2024-10-09 06:16 UTC, Alxe commented
> @Alxe or @ManuelJNunez validation test is failing. Is this normal?

The failure is due to the native libraries not having a symbol (`RTI_Connector_return_loan`) I added in a patch release:
```
AttributeError: /rti/jenkins/workspace/ticonnextdds-connector-py_PR-185/rticonnextdds_connector/../rticonnextdds-connector/lib/linux-x64/librtiddsconnector.so: undefined symbol: RTI_Connector_return_loan
```

See [this comment](https://github.com/rticommunity/rticonnextdds-connector-py/pull/179#issuecomment-2367570002) on the PR for more context.

2024-10-09 06:20 UTC, ManuelJNunez commented
> > @Alxe or @ManuelJNunez validation test is failing. Is this normal?
> 
> The failure is due to the native libraries not having a symbol (`RTI_Connector_return_loan`) I added in a patch release:
> 
> ```
> AttributeError: /rti/jenkins/workspace/ticonnextdds-connector-py_PR-185/rticonnextdds_connector/../rticonnextdds-connector/lib/linux-x64/librtiddsconnector.so: undefined symbol: RTI_Connector_return_loan
> ```
> 
> See [this comment](https://github.com/rticommunity/rticonnextdds-connector-py/pull/179#issuecomment-2367570002) on the PR for more context.

Can we suppose that this will work once we have the new libraries built?

2024-10-09 06:22 UTC, Alxe commented
> Can we suppose that this will work once we have the new libraries built?

I would assume yes, as I tested my changes locally. The current subrepository libraries have `6.1.2.17` instead of `6.1.2.21`, which is why we're failing.

2024-10-09 06:24 UTC, Alxe requested changes
We need to make a decision if we're fetching the native libraries from the internal repositories, or from the submodule. If the former, which I would prefer, we need to delete the submodule from this repository.

```
git rm rticonnextdds-connector .gitmodules
```

2024-10-10 09:00 UTC, Alxe approved these changes
@ManuelJNunez will handle the pending AI for this PR. We can merge it.

2024-10-10 09:05 UTC, ManuelJNunez approved these changes

2024-10-10 11:57 UTC, merged