REL-2593: updating connector-py release notes for 6.1.2.21
rticommunity/rticonnextdds-connector-py pull request #189
Opened 2024-10-16 18:57 UTC by rkorte

Here is the documentation output associated with this PR: https://jenkins-community.rti.com/job/ci/job/Connector-PY/job/rticonnextdds-connector-py-doc/view/change-requests/job/PR-189/Connector_20Documentation/release_notes.html

2024-10-16 18:58 UTC, rkorte commented
@Alxe, do we need to add return_samples to the documentation, perhaps [here](https://jenkins-community.rti.com/job/ci/job/Connector-PY/job/rticonnextdds-connector-py-doc/job/release%252Fconnector%252F1.2.4/Connector_20Documentation/input.html#input-class)?

Can you update the documentation in this PR, and I will review it?

2024-10-16 18:59 UTC, rkorte commented on docs/release_notes.rst
> +.. code:: python
@Alxe, correct code argument?

2024-10-16 19:01 UTC, rkorte commented on docs/copyright_license.rst
The [json-parser](https://jenkins-community.rti.com/job/ci/job/Connector-PY/job/rticonnextdds-connector-py-doc/job/release%252Fconnector%252F1.2.4/Connector_20Documentation/copyright_license.html) entry in this file does not exactly match the [3rdParty document in the Pro installation](https://docserver.rti.com/docs/connext-docs/6.1.2.21/doc/manuals/connext_dds_professional/release_notes_3rdparty/RTI_ConnextDDS_3rdPartySoftware_CoreLibraries.pdf). Which one should I update to match the other?

2024-10-17 09:42 UTC, Alxe commented
> @Alxe, do we need to add return_samples to the documentation, perhaps [here](https://jenkins-community.rti.com/job/ci/job/Connector-PY/job/rticonnextdds-connector-py-doc/job/release%252Fconnector%252F1.2.4/Connector_20Documentation/input.html#input-class)?
> 
> Can you update the documentation in this PR, and I will review it?

I think we already have that in the documentation?
![image](https://github.com/user-attachments/assets/97d9ec7e-b6f8-49ba-b551-2bbb34b8776c)

2024-10-17 09:43 UTC, Alxe commented on docs/release_notes.rst
> +.. code:: python
Yes, that'll be alright. :)

2024-10-17 09:45 UTC, Alxe commented on docs/copyright_license.rst
`https://github.com/udp/json-parser` (Connector documentation) redirects to `https://github.com/json-parser/json-parser` (3rd Party document), so I'd say we need to update this section.

2024-10-17 09:45 UTC, Alxe requested changes
Update 3rd Party notes.

2024-10-17 17:48 UTC, rkorte commented on docs/copyright_license.rst
@Alxe, I updated the (c) line, too, to match what we have on https://github.com/json-parser/json-parser

2024-10-17 18:06 UTC, Alxe approved these changes

2024-10-17 18:18 UTC, merged