Updated the Platforms notes to include Ubuntu 16.04 (x64 + ARMv8)
rticommunity/rticonnextdds-connector-py pull request #68
Opened 2021-03-12 08:24 UTC by samuelraeburn

2021-03-12 15:51 UTC, alexcamposruiz requested changes

2021-03-12 15:51 UTC, alexcamposruiz commented on docs/release_notes.rst
> +  * Ubuntu 16.04, 18.04 LTS (64-bit Arm® v8)
Add Arm8 support to What's New

2021-03-15 08:53 UTC, samuelraeburn commented
> Add Raspbian Wheezy 7 on Arm v6

We have no infrastructure to test this right now. I'm fairly sure it will run on that architecture, but without any way of confirming that I do not know if we should add it to the release notes

2021-03-24 14:07 UTC, alexcamposruiz approved these changes

2021-03-24 14:54 UTC, adelleolson approved these changes

2021-03-24 14:55 UTC, merged