CON-223: Removed ability to set max_objects_per_thread
rticommunity/rticonnextdds-connector-py pull request #78
Opened 2021-05-25 12:47 UTC by samuelraeburn

The behaviour of max_objects_per_thread has changed in the core, and it now
grows dynamically. There is no longer any reason to allow it to be set in
Connector.

2021-05-25 14:20 UTC, samuelraeburn commented
[ ] Wait for ironside release. Until then we will not have the required change in core libs.

2021-06-02 21:06 UTC, alexcamposruiz requested changes

2021-06-02 21:06 UTC, alexcamposruiz commented on rticonnextdds_connector/rticonnextdds_connector.py
> -    def set_max_objects_per_thread(value):
We should deprecate the function and leave empty its implementation so we don't break existing applications.

2021-06-18 23:48 UTC, alexcamposruiz approved these changes

2021-06-24 12:59 UTC, merged